version: '3.8'
services:
  postgres:
    image: postgres:15.6-bullseye
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
  rabbitmq:
    image: rabbitmq:3.13.0-management
    ports:
      - 15672:15672
      - 5672:5672
#TODO: find a way to setup password
#    entrypoint:
#      - RABBITMQ_DEFAULT_USER=admin
#      - RABBITMQ_DEFAULT_PASS=rabbitmq